version: "3.3"
services:
  bot:
    build:
      context: bot/.
    image: mem_frog_bot:0.7
    volumes:
      - ./bot/config.py:/app/config.py
  redis:
    container_name: redis
    image: redis:6.0-alpine3.12
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass REDIS_PASS'
      #${REDIS_PASS}'
    volumes:
      - ./Redis/data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
#  rabbitmq:
#    image: rabbitmq:latest
#    container_name: rabbitmq
##    volumes:
##      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
##      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
##      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
#    environment:
#      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#    ports:
#      - 5672:5672
#      - 15672:15672